version: '3'

services:
  database:
    image: mariadb:10.8.3
    restart: always
    environment:
      MYSQL_DATABASE: ${POSTGRES_DB:-shop}
      MYSQL_USER: ${POSTGRES_USER:-symfony}
      MYSQL_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      MYSQL_ROOT_PASSWORD: ${DB_PASS:-rootPass}
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql/data:rw

volumes:
  db-data:
