framework:
  messenger:
    default_bus: command.bus
    buses:
      command.bus:
        middleware:
          - doctrine_ping_connection

      query.bus: ~

      #      event.bus:
      #        default_middleware: allow_no_handlers

    transports:
      #            amqp: '%env(MESSENGER_TRANSPORT_DSN)%/commands'
      sync: 'sync://'

when@test:
  framework:
    messenger:
      transports:
        async: 'in-memory://'